version: '2'

services:
 transmission:
  image: flackdl/rpi-transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /media/pi/blackhole/torrents:/data
  env_file:
    - .env
  environment:
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.1.0/24
 proxy:
  image: flackdl/rpi-transmission-openvpn-proxy
  links:
    - transmission
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro

 sonarr:
  image: lsioarmhf/sonarr
  restart: always
  ports:
    - "8989:8989"
  volumes:
    - /media/pi/blackhole/torrents/completed:/downloads
    - /media/pi/blackhole/torrents/completed:/tv
    - sonarr:/config 

 jackett:
  image: lsioarmhf/jackett
  restart: always
  ports:
    - "9117:9117"
  volumes:
    - /media/pi/blackhole/torrents/completed:/downloads
    - jackett:/config 

 ombi:
  image: lsioarmhf/ombi
  restart: always
  ports:
    - "3579:3579"
  volumes:
    - /media/pi/blackhole/torrents/completed:/downloads:ro
    - ombi:/config 

 samba:
  image: flackdl/samba-armhf
  restart: always
  ports:
    - "137:137"
    - "138:138"
    - "139:139"
    - "445:445"
  command: -u "${SMB_USER};${SMB_PASS}" -s "torrents;/torrents" -g "min protocol = CORE"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /media/pi/blackhole/torrents/completed:/torrents:ro

volumes:
  sonarr:
  ombi:
  jackett:
