version: '2'

services:
 transmission:
  image: flackdl/rpi-transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${TORRENTS_DIR}:/data
  env_file:
    - .env
  environment:
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.1.0/24
 proxy:
  image: flackdl/rpi-transmission-openvpn-proxy
  restart: always
  depends_on:
    - transmission
  links:
    - transmission
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro

 jackett:
  image: lsioarmhf/jackett
  restart: always
  ports:
    - "9117:9117"
  volumes:
    - ${TORRENTS_WATCH_DIR}:/downloads
    - ${TORRENTS_DIR}/jackett:/config 

 samba:
  image: flackdl/samba-armhf
  restart: always
  ports:
    - "137:137/udp"
    - "138:138/udp"
    - "139:139"
    - "445:445"
  env_file:
    - .env
  command: -n -u "${SMB_USER};${SMB_PASS}" -s "torrents;/torrents" -g "min protocol = CORE" -g "netbios name = rpi" -g "workgroup = blackhole"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${TORRENTS_DIR}:/torrents:ro

 ssh-to-docker-host:
   build: https://github.com/flackdl/rpi-docker-autossh.git
   restart: always
   env_file:
    - .env
   volumes:
    - $PWD/id_rsa:/id_rsa
   dns:
    - 8.8.8.8
    - 4.2.2.4
