#cloud-config

hostname: rpi
manage_etc_hosts: true
# allow password authentication
ssh_pwauth: true

users:
  - name: pi
    gecos: "rpi"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    # TODO - REPLACE
    plain_text_passwd: cookie123
    lock_passwd: false
    chpasswd:
      expire: false

#package_update: true
#package_upgrade: true
packages:
 - docker.io
 - docker-compose
 - fail2ban
 - autossh

write_files:

- path: /etc/systemd/system/autossh.service
  # TODO - REPLACE PORT AND DOMAIN
  content: |
    [Unit]
    Description=Autossh rpi
    After=network.target
    [Service]
    Type=simple
    User=pi
    Restart=always
    ExecStart=/usr/bin/autossh -N -M 0  -o "StrictHostKeyChecking=no" -o "PubkeyAuthentication=yes" -o "PasswordAuthentication=no" -i /home/pi/autossh_id_rsa -R XXXX:localhost:22 autossh@XXX.XXX.com
    RestartSec=3
    StartLimitBurst=5
    StartLimitIntervalSec=0
    [Install]
    WantedBy=multi-user.target
  permissions: '0600'

- path: /home/pi/autossh_id_rsa
  # TODO - POPULATE WITH PRIVATE SSH KEY
  content: |
  owner: 'pi:pi'
  permissions: '0600'
  defer: true
- path: /home/pi/.env
  # TODO - POPULATE WITH NEFARIOUS SETTINGS ENV FILE
  content: |
  owner: 'pi:pi'
  permissions: '0600'
  defer: true

# these will be ran once on first boot only
runcmd:
  - 'systemctl enable --now autossh'
  - 'systemctl daemon-reload'
  - 'git -C /home/pi clone https://github.com/flackdl/rpi-pirate.git'
  - 'mv /home/pi/.env /home/pi/rpi-pirate'
  - 'chown -R pi:pi /home/pi/rpi-pirate'
  - 'su -c "cd /home/pi/rpi-pirate; docker-compose up -d" pi'
